In [103]:
#wczytanie bibliotek
import pandas as pd
import numpy as np
import random
from sklearn.metrics.pairwise import pairwise_distances

In [104]:
# 1. Wczytanie danych produkt-kategoria
dane_kategorie = pd.read_csv('C:\\Users\\mateu\\OneDrive\\Pulpit\\wyg.dane_kategorie2.csv')
kategorie = dane_kategorie.pivot_table(index='kategoriaid',columns='produktid',values='value')
kategorie.head(15)
# 2. Wczytanie danych klient-produkt
dane_aktywnosc = pd.read_csv('C:\\Users\\mateu\\OneDrive\\Pulpit\\wyg.dane_aktywnosc2.csv')
aktywnosc = dane_aktywnosc.pivot_table(index='klientid',columns='produktid',values='zdarzenie')
aktywnosc = aktywnosc.fillna(0)

In [105]:
#aktywnosc
with pd.option_context('display.max_rows', 12, 'display.max_columns', 12):  # more options can be specified also
   print(aktywnosc)
#aktywnosc


produktid  1    2    3    4    5    6    ...  604  605  606  607  608  609
klientid                                 ...                              
1          0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
2          0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
3          0.0  0.0  0.0  0.0  2.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
4          0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
5          0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
6          0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
...        ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
75         0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
76         0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
77         5.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
78         0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
79         0.0  0.0  0.0 

In [106]:
kategorie

produktid    1    2    3    4    5    6    7    8    9    10   ...  600  601  \
kategoriaid                                                    ...             
1              1    1    1    1    0    0    0    0    1    1  ...    1    1   
2              0    1    0    1    0    1    1    1    0    1  ...    0    1   
3              1    1    1    1    1    0    0    0    1    0  ...    1    0   
4              1    1    1    0    1    0    0    1    1    0  ...    1    0   
5              1    0    1    0    1    1    1    0    0    0  ...    1    0   
6              1    0    1    1    1    1    0    1    1    1  ...    0    0   
7              0    1    0    0    0    0    0    0    1    0  ...    0    0   
8              1    0    0    1    0    1    1    0    0    0  ...    0    0   

produktid    602  603  604  605  606  607  608  609  
kategoriaid                                          
1              0    1    0    1    0    1    1    0  
2              0    1    0    0    1    1    0    0  
3              0    1    1    1    1    0    1    1  
4              0    1    0    0    0    0    0    1  
5              0    0    0    1    1    0    0    1  
6              0    1    0    0    1    1    1    1  
7              1    1    1    1    0    0    1    1  
8              0    1    0    1    1    0    0    0  

[8 rows x 609 columns]

In [107]:
# 3. Inicjalizacja populacji
docKlient = aktywnosc.iloc[[2]] #docelowy klient - klient o ID: 3
docKlient

produkty_obejrzane = docKlient.loc[:, (docKlient != 0).any()]
produkty_obejrzane   

populacja_aktywnosc = aktywnosc.drop(columns = produkty_obejrzane)
populacja_kategorie = kategorie.drop(columns = produkty_obejrzane)

M = 150 # liczba osobnikow w populacji
n= 4 # liczba genow osobnika
populacja_osobnikow_kategorie = np.split(populacja_kategorie, M, axis=1)
populacja_osobnikow_aktywnosc = np.split(populacja_aktywnosc, M, axis=1)

In [126]:
docKlient

produktid  1    2    3    4    5    6    7    8    9    10   ...  600  601  \
klientid                                                     ...             
3          0.0  0.0  0.0  0.0  2.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   

produktid  602  603  604  605  606  607  608  609  
klientid                                           
3          0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[1 rows x 609 columns]

In [108]:
population = []
for x in range(len(populacja_osobnikow_kategorie)):
    population.append(populacja_osobnikow_kategorie[x].columns.values)                      
#population
population

#population

[array([1, 2, 3, 4], dtype=int64),
 array([6, 7, 8, 9], dtype=int64),
 array([10, 11, 12, 13], dtype=int64),
 array([14, 15, 16, 17], dtype=int64),
 array([18, 19, 20, 21], dtype=int64),
 array([22, 23, 24, 25], dtype=int64),
 array([26, 27, 28, 29], dtype=int64),
 array([30, 31, 32, 33], dtype=int64),
 array([34, 35, 36, 37], dtype=int64),
 array([38, 39, 40, 41], dtype=int64),
 array([42, 43, 44, 45], dtype=int64),
 array([46, 47, 48, 49], dtype=int64),
 array([50, 51, 52, 53], dtype=int64),
 array([54, 55, 56, 57], dtype=int64),
 array([58, 59, 60, 61], dtype=int64),
 array([62, 63, 64, 65], dtype=int64),
 array([66, 67, 68, 69], dtype=int64),
 array([70, 71, 72, 73], dtype=int64),
 array([74, 75, 76, 77], dtype=int64),
 array([78, 79, 80, 81], dtype=int64),
 array([82, 83, 84, 85], dtype=int64),
 array([86, 87, 88, 89], dtype=int64),
 array([90, 91, 92, 93], dtype=int64),
 array([94, 95, 96, 97], dtype=int64),
 array([ 98,  99, 100, 101], dtype=int64),
 array([102, 103, 104, 105], 

In [109]:
# Konwersja binarna osobnikow
def vec_bin_array(arr, m):
    """
    Arguments: 
    arr: Numpy array of positive integers
    m: Number of bits of each integer to retain

    Returns a copy of arr with every element replaced with a bit vector.
    Bits encoded as int8's.
    """
    to_str_func = np.vectorize(lambda x: np.binary_repr(x).zfill(m))
    strs = to_str_func(arr)
    ret = np.zeros(list(arr.shape) + [m], dtype=np.int8)
    for bit_ix in range(0, m):
        fetch_bit_func = np.vectorize(lambda x: x[bit_ix] == '1')
        ret[...,bit_ix] = fetch_bit_func(strs).astype("int8")

    return ret 
popop = []
for x in range(M):
    popop.append(vec_bin_array(population[x],9))
#popop

In [110]:
# Korelacja osobnikow

def Korelacja_osobnikow(populacja,populacja_binarnie):
    population_fitness_dictionary = dict([])
    for x in range(M):
        jac_sim = 1- pairwise_distances(populacja[x].T, metric = "hamming")
        # optionally convert it to a DataFrame
        jac_sim = pd.DataFrame(jac_sim, index=populacja[x].columns,
                           columns=populacja[x].columns)
        population_fitness_dictionary[str(populacja_binarnie[x])] = jac_sim.sum().sum()
    return population_fitness_dictionary
population_fitness_dictionary = Korelacja_osobnikow(populacja_osobnikow_kategorie,population)
population_fitness_dictionary

{'[1 2 3 4]': 10.75,
 '[6 7 8 9]': 9.25,
 '[10 11 12 13]': 9.75,
 '[14 15 16 17]': 12.0,
 '[18 19 20 21]': 9.5,
 '[22 23 24 25]': 9.75,
 '[26 27 28 29]': 10.5,
 '[30 31 32 33]': 10.0,
 '[34 35 36 37]': 10.5,
 '[38 39 40 41]': 9.0,
 '[42 43 44 45]': 9.25,
 '[46 47 48 49]': 12.75,
 '[50 51 52 53]': 9.25,
 '[54 55 56 57]': 9.0,
 '[58 59 60 61]': 10.75,
 '[62 63 64 65]': 10.5,
 '[66 67 68 69]': 11.25,
 '[70 71 72 73]': 10.25,
 '[74 75 76 77]': 9.25,
 '[78 79 80 81]': 10.25,
 '[82 83 84 85]': 9.25,
 '[86 87 88 89]': 11.25,
 '[90 91 92 93]': 10.25,
 '[94 95 96 97]': 11.0,
 '[ 98  99 100 101]': 10.0,
 '[102 103 104 105]': 10.75,
 '[106 107 108 109]': 11.0,
 '[110 111 112 113]': 8.75,
 '[114 115 116 117]': 10.0,
 '[118 119 120 121]': 9.0,
 '[122 123 124 125]': 8.75,
 '[126 127 128 129]': 11.75,
 '[130 131 132 133]': 10.25,
 '[134 135 136 137]': 11.0,
 '[138 139 140 141]': 9.75,
 '[142 143 144 145]': 9.75,
 '[146 147 148 149]': 9.5,
 '[150 151 152 153]': 10.0,
 '[154 155 156 157]': 10.25,
 '[15

In [111]:
# 5. Selekcja metoda koła ruletki

def get_probability_list(dictionary):
    fitness = dictionary.values()
    total_fit = float(sum(fitness))
    relative_fitness = [f/total_fit for f in fitness]
    probabilities = [sum(relative_fitness[:i+1]) 
                     for i in range(len(relative_fitness))]
    return probabilities
#prob = get_probability_list(population_fitness_dictionary)

def roulette_wheel_pop(population, probabilities, number):
    chosen = []
    for n in range(number):
        r = random.random()
        for (i, individual) in enumerate(population):
            if r <= probabilities[i]:
                chosen.append(list(individual))
                break
    return chosen

In [112]:
# 6. Krzyzowanie 
def crossover4(a, b, crossover_point):
    a1 = a[:]
    b1 = b[:]
    for i in range(crossover_point):
        a1[i], b1[i] = b1[i], a1[i]
    return [a1, b1]

In [113]:
#7. Mutacja
def mutation(pop_after_cross,mutation_rate):
    population_nextgen = []
    for i in range(0,len(pop_after_cross)):
        chromosome = pop_after_cross[i]
        for j in range(len(chromosome)):
            if random.random() < mutation_rate:
                chromosome[j]= not chromosome[j]
        population_nextgen.append(chromosome)
    #print(population_nextgen)
    return population_nextgen

In [114]:
# 8. Podobienstwo uzytkownikow
def Podobienstwo1(populacja,populacja_binarnie):
    population_fitness_dictionary1 = dict([])
    for x in range(M):
        pearson_sim = 1- pairwise_distances(populacja[x].T, metric = "correlation")
        # optionally convert it to a DataFrame
        pearson_sim = pd.DataFrame(pearson_sim, index=populacja[x].columns,
                           columns=populacja[x].columns)
        population_fitness_dictionary1[str(populacja_binarnie[x])] = pearson_sim.sum().sum()
    return population_fitness_dictionary1
population_fitness_dictionary1 = Podobienstwo1(populacja_osobnikow_kategorie,population)
population_fitness_dictionary1

{'[1 2 3 4]': 4.494427190999916,
 '[6 7 8 9]': 2.516397779494322,
 '[10 11 12 13]': 3.616935553839011,
 '[14 15 16 17]': 7.965053343632599,
 '[18 19 20 21]': 3.1106078436554796,
 '[22 23 24 25]': 3.6169355538390113,
 '[26 27 28 29]': 6.42438923155396,
 '[30 31 32 33]': 4.462951460666611,
 '[34 35 36 37]': 4.425082411045975,
 '[38 39 40 41]': 3.850961866297163,
 '[42 43 44 45]': 2.0463365543335295,
 '[46 47 48 49]': 9.915322230804945,
 '[50 51 52 53]': 2.2274777883906918,
 '[54 55 56 57]': 1.7481941573335575,
 '[58 59 60 61]': 5.6825266718163,
 '[62 63 64 65]': 5.09946222565531,
 '[66 67 68 69]': 7.129983712800161,
 '[70 71 72 73]': 4.516397779494322,
 '[74 75 76 77]': 3.035190936333361,
 '[78 79 80 81]': 5.3049694255515965,
 '[82 83 84 85]': 1.068790769477029,
 '[86 87 88 89]': 6.516397779494323,
 '[90 91 92 93]': 3.6968975528613486,
 '[94 95 96 97]': 6.133333333333334,
 '[ 98  99 100 101]': 6.031457407602224,
 '[102 103 104 105]': 3.1759546816668074,
 '[106 107 108 109]': 5.3880297320

In [125]:
liczba_generacji = 200 # liczba generacji
M = 150 # liczba osobnikow w populacji
n= 4 # liczba produktow w osobniku
p_mutacji = 0.1 # Prawdopodobienstwo mutacji
rand1 = random.randint(1,3)
rand2 = random.randint(1,8)
for i in range(liczba_generacji):
    wynik_korelacji = Korelacja_osobnikow(populacja_osobnikow_kategorie,popop)
    prob = get_probability_list(wynik_korelacji)
    wynik_r1 = roulette_wheel_pop(popop,prob,M)
    crossover4(wynik_r1[rand2][rand1],wynik_r1[rand2][rand1],3)
    mutation(wynik_r1[rand2],p_mutacji)   
    wynik_podobienstwa = Podobienstwo1(populacja_osobnikow_aktywnosc,wynik_r1)    
    prob = get_probability_list(wynik_podobienstwa)
    wynik_r2 = roulette_wheel_pop(wynik_r1,prob,M)        

posortowane_wyniki = {k: v for k, v in sorted(wynik_podobienstwa.items(), key=lambda item: item[1], reverse = True)}
posortowane_wyniki



{'[array([0, 1, 0, 1, 1, 0, 0, 1, 0], dtype=int8), array([0, 1, 0, 1, 1, 0, 0, 1, 1], dtype=int8), array([0, 1, 0, 1, 1, 0, 1, 0, 0], dtype=int8), array([0, 1, 0, 1, 1, 0, 1, 0, 1], dtype=int8)]': 6.0,
 '[array([1, 1, 0, 0, 1, 0, 0, 1, 0], dtype=int8), array([0, 1, 0, 0, 1, 1, 0, 1, 1], dtype=int8), array([0, 1, 0, 0, 1, 1, 1, 0, 0], dtype=int8), array([0, 1, 0, 0, 1, 1, 1, 0, 1], dtype=int8)]': 5.949367088607588,
 '[array([0, 1, 1, 1, 1, 1, 1, 0, 0], dtype=int8), array([0, 1, 1, 0, 1, 1, 0, 0, 1], dtype=int8), array([0, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8), array([0, 0, 1, 1, 1, 1, 1, 0, 1], dtype=int8)]': 5.551664255976423,
 '[array([1, 1, 0, 1, 0, 1, 0, 1, 1], dtype=int8), array([1, 0, 0, 1, 1, 0, 1, 0, 0], dtype=int8), array([1, 0, 0, 1, 1, 0, 0, 0, 1], dtype=int8), array([1, 0, 0, 0, 1, 0, 1, 1, 1], dtype=int8)]': 4.805699071455262,
 '[array([1, 0, 1, 1, 1, 0, 1, 1, 0], dtype=int8), array([0, 1, 1, 0, 0, 0, 1, 0, 0], dtype=int8), array([1, 0, 1, 0, 1, 0, 0, 0, 0], dtype=int8), arr

In [124]:
wynik =[]
for x in range(len(wynik_r2[0])):
    wynik.append(int(''.join(str(i) for i in wynik_r2[0][x]), 2))
wynik

[301, 125, 318, 366]

In [100]:
#len(wynik_r1[3][1])
wynik_podobienstwa1 = {k: v for k, v in sorted(wynik_podobienstwa.items(), key=lambda item: item[1], reverse = True)}
wynik_podobienstwa1
#posortowane_wyniki

{'[array([1, 0, 1, 1, 1, 0, 1, 0, 1], dtype=int8), array([1, 0, 1, 1, 1, 0, 1, 1, 0], dtype=int8), array([1, 0, 1, 1, 1, 0, 1, 1, 1], dtype=int8), array([1, 0, 1, 1, 1, 1, 0, 0, 0], dtype=int8)]': 6.0,
 '[array([1, 0, 0, 1, 0, 0, 1, 1, 1], dtype=int8), array([1, 0, 0, 1, 0, 0, 1, 1, 1], dtype=int8), array([1, 0, 0, 1, 0, 1, 0, 0, 0], dtype=int8), array([1, 0, 0, 1, 0, 1, 0, 0, 0], dtype=int8)]': 5.873417721518987,
 '[array([1, 0, 0, 1, 0, 0, 0, 1, 1], dtype=int8), array([1, 0, 0, 1, 0, 0, 0, 1, 1], dtype=int8), array([1, 0, 0, 1, 0, 0, 1, 0, 0], dtype=int8), array([1, 0, 0, 1, 0, 0, 1, 0, 0], dtype=int8)]': 5.551664255976423,
 '[array([0, 1, 1, 1, 1, 0, 1, 0, 0], dtype=int8), array([0, 1, 1, 1, 1, 0, 1, 0, 1], dtype=int8), array([0, 1, 1, 1, 1, 0, 1, 1, 0], dtype=int8), array([0, 1, 1, 1, 1, 0, 1, 1, 1], dtype=int8)]': 4.805699071455262,
 '[array([0, 1, 0, 1, 1, 1, 1, 1, 0], dtype=int8), array([0, 1, 0, 1, 1, 1, 1, 1, 1], dtype=int8), array([0, 1, 1, 0, 0, 0, 0, 0, 0], dtype=int8), arr